name: fr_realtime
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # C
  cupertino_icons: ^1.0.8

  # G
  google_mlkit_face_detection: ^0.13.1

  # D
  dio: ^5.8.0+1

  # T
  tflite_flutter: ^0.11.0

  # I
  image: ^4.2.0
  intl: ^0.20.2

  # C
  camera: ^0.11.1

  # S
  sqflite: ^2.4.2
  
  # P
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
